baseURL = "https://joonvena.github.io/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "anatole"

[params]
title = "Joonas Ven채l채inen"
author = "Joonas Ven채l채inen"
description = "DevOps Engineer"
profilePicture = "images/profile.jpg"
displayMode = "light"
disableThemeSwitcher = true
